import java.util.ArrayList;
public class driver{
  public static void main(String[] args){
    //Testing Square Root
    System.out.println("----------Testing sqrt(num, tolerance)----------\n");
    System.out.println("Compare your answer to the Math.sqrt(num) answer!\n");
    System.out.println("Sqrt(1, 0.001): "+recursion.sqrt(1, 0.001));
    System.out.println("  Math.sqrt(1): "+Math.sqrt(1));
    System.out.println("\nSqrt(2, 0.113): "+recursion.sqrt(2, 0.113));
    System.out.println("  Math.sqrt(2): "+Math.sqrt(2));
    System.out.println("\nSqrt(10, 0.000002): "+recursion.sqrt(10, 0.000002));
    System.out.println("     Math.sqrt(10): "+Math.sqrt(10));
    System.out.println("\nSqrt(25, 0.0004): "+recursion.sqrt(25, 0.0004));
    System.out.println("   Math.sqrt(25): "+Math.sqrt(25));
    System.out.println("\nSqrt(36, 0.025): "+recursion.sqrt(36, 0.025));
    System.out.println("  Math.sqrt(36): "+Math.sqrt(36));
    System.out.println("\nSqrt(0, 0.0000000001): "+recursion.sqrt(0, 0.0000000001));
    System.out.println("         Math.sqrt(0): "+Math.sqrt(0));
    System.out.println("\nSqrt(1999, 0.00000006): "+recursion.sqrt(1999, 0.00000006));
    System.out.println("       Math.sqrt(1999): "+Math.sqrt(1999));
    System.out.println("\nSqrt(287, 0.000078): "+recursion.sqrt(287, 0.000078));
    System.out.println("     Math.sqrt(287): "+Math.sqrt(287));
    System.out.println("\nSqrt(72, 0.000012): "+recursion.sqrt(72, 0.000012));
    System.out.println("     Math.sqrt(72): "+Math.sqrt(72));
    System.out.println("\nSqrt(6, 0.0004): "+recursion.sqrt(6, 0.00004));
    System.out.println("   Math.sqrt(6): "+Math.sqrt(6));

    System.out.println("\n\n----------Testing fib----------\n");
    System.out.println("fib(0) --> 0: "+recursion.fib(0));
    System.out.println("fib(1) --> 1: "+recursion.fib(1));
    System.out.println("fib(2) --> 1: "+recursion.fib(2));
    System.out.println("fib(3) --> 2: "+recursion.fib(3));
    System.out.println("fib(4) --> 3: "+recursion.fib(4));
    System.out.println("fib(5) --> 5: "+recursion.fib(5));
    System.out.println("fib(6) --> 8: "+recursion.fib(6));
    System.out.println("fib(7) --> 13: "+recursion.fib(7));
    System.out.println("fib(8) --> 21: "+recursion.fib(8));
    System.out.println("fib(9) --> 34: "+recursion.fib(9));
    System.out.println("fib(10) --> 55: "+recursion.fib(10));
    System.out.println("fib(11) --> 89: "+recursion.fib(11));
    System.out.println("fib(12) --> 144: "+recursion.fib(12));
    System.out.println("fib(13) --> 233: "+recursion.fib(13));
    System.out.println("fib(14) --> 377: "+recursion.fib(14));
    System.out.println("fib(15) --> 610: "+recursion.fib(15));
    System.out.println("\n-------Okay you get the idea... I'm too lazy to type the rest. :P-------\n");
    System.out.println("fib(16)"+recursion.fib(16));
    System.out.println("fib(17)"+recursion.fib(17));
    System.out.println("fib(18)"+recursion.fib(18));
    System.out.println("fib(19)"+recursion.fib(19));
    System.out.println("fib(20)"+recursion.fib(20));
    System.out.println("fib(21)"+recursion.fib(21));
    System.out.println("fib(22)"+recursion.fib(22));
    System.out.println("fib(23)"+recursion.fib(23));
    System.out.println("fib(24)"+recursion.fib(24));
    System.out.println("fib(25)"+recursion.fib(25));
    System.out.println("fib(26)"+recursion.fib(26));
    System.out.println("fib(27)"+recursion.fib(27));
    System.out.println("fib(28)"+recursion.fib(28));
    System.out.println("fib(29)"+recursion.fib(29));
    System.out.println("fib(30)"+recursion.fib(30));
    System.out.println("fib(31)"+recursion.fib(31));
    System.out.println("fib(32)"+recursion.fib(32));
    System.out.println("fib(33)"+recursion.fib(33));
    System.out.println("fib(34)"+recursion.fib(34));
    System.out.println("fib(35)"+recursion.fib(35));
    System.out.println("fib(36)"+recursion.fib(36));
    System.out.println("fib(37)"+recursion.fib(37));
    System.out.println("fib(38)"+recursion.fib(38));
    System.out.println("fib(39)"+recursion.fib(39));
    System.out.println("fib(40)"+recursion.fib(40));
    System.out.println("fib(41)"+recursion.fib(41));
    System.out.println("fib(42)"+recursion.fib(42));
    System.out.println("fib(43)"+recursion.fib(43));
    System.out.println("fib(44)"+recursion.fib(44));
    System.out.println("fib(45)"+recursion.fib(45));
    System.out.println("fib(46)"+recursion.fib(46));
    System.out.println("\n-------fib will start being weird at fib(47)-------\n");
    System.out.println("fib(47)"+recursion.fib(47));
    System.out.println("fib(48)"+recursion.fib(48));
    System.out.println("fib(49)"+recursion.fib(49));

    System.out.println("\n\n-------Testing makeAllSums-------\n");
    System.out.println("Note: order doesn't matter!!!");
    System.out.println("makeAllSums(0) --> [0] \n                   "+recursion.makeAllSums(0).toString());
    System.out.println("makeAllSums(1) --> [0, 1] \n                   "+recursion.makeAllSums(1).toString());
    System.out.println("makeAllSums(2) --> [0, 1, 2, 3] \n                   "+recursion.makeAllSums(2).toString());
    System.out.println("makeAllSums(3) --> [0, 1, 2, 3, 3, 4, 5, 6] \n                   "+recursion.makeAllSums(3).toString());
  }
}
